### PR TITLE
Add test-crawl command to run locally

### PR DESCRIPTION
**Pull request by vshlapakov**
As a part of the work to allow running custom images locally, there's a proposal to add a new command to the current layer: similar to the `start-crawl` logic but significantly simplified:
- requiring only the minimal set of environment vars to start
- with default stdout/stderr output
- without default settings required for Scrapy Cloud

The library is very well-designed, so it's straightforward to reuse the existing helpers, and I want to keep it well-designed, so my main concerns here are mostly about naming (module `local`, command `test-crawl`). Maybe there's anything else you would add to the changes.

Related changes in shub tool (I'll create a PR when we agree on the design)
https://github.com/scrapinghub/shub/compare/run-custom-image-locally?expand=1

Please, take a look and let me know your thoughts.

### CODE REVIEW

**Comment by dangra** [comment]
what are the reasons not to use `start-crawl` entrypoint for local runs too?

**Comment by vshlapakov** [comment]
>  It doesn't look good that we need a different command to run locally vs SC.

Agree, I'd prefer to avoid it too

> The FIFO file and a dummy consumer is something we can provide easily in shub tool.

That could work too. My main concerns here are:
- the additional complexity of shub (create a fifo file, share it with a container (via volume I guess), prepare a consumer logic to log the file data, run it in parallel with the container, do cleanup)
- a necessity to provide a bunch of fake environment vars to the container (job id, auth etc)

Though, it looks simpler to have it all in shub, rather than updating all stacks and maintaining the logic in the intermediate layer. It should also work better if a custom image doesn't use sh-ep-scrapy at all. I'll do another attempt to implement it on shub side only, and ping you when it's ready. Thanks.

**Comment by dangra** [comment]
> Though, it looks simpler to have it all in shub, rather than updating all stacks and maintaining the logic in the intermediate layer. It should also work better if a custom image doesn't use sh-ep-scrapy at all. I'll do another attempt to implement it on shub side only, and ping you when it's ready. Thanks.

Yes, all of that is needed but it is also the way forward to transparently support non sh-ep-scrapy based images. thanks!

**Comment by vshlapakov** [comment]
Closing in favor of https://github.com/scrapinghub/shub/pull/346.

**Pull request closed without merging**
